//
// Copyright (c) Fela Ameghino 2015-2026
//
// Distributed under the GNU General Public License v3.0. (See accompanying
// file LICENSE or copy at https://www.gnu.org/licenses/gpl-3.0.txt)
//

using System;
using System.IO;

namespace Telegram.Native
{
    /// <summary>
    /// Finds the data files the native modules need: the language identification model and the
    /// libprisma grammars.
    ///
    /// <para>On Windows both paths were literals relative to the package -- Telegram.Native asked
    /// for <c>"Assets\\langid_model.smfb.jpg"</c> and <c>"Assets\\grammars.dat"</c> and got away
    /// with it, because a packaged UWP app runs with its install directory as the working
    /// directory. Neither half of that holds here: there is no package, and the working directory
    /// is wherever the user happened to launch from (<c>/home/user</c> for a .desktop launcher,
    /// <c>/</c> for a systemd unit), so a relative path resolves to nothing.</para>
    ///
    /// <para>So the path is decided HERE, in managed code, and passed to the library: the ABI takes
    /// it as an argument (<c>unigram_langid_init</c>, <c>unigram_highlight_init</c>) and its
    /// relative defaults exist only so the engines' own smoke tests still run. The order below
    /// answers "where can this file be?" from most to least specific.</para>
    ///
    /// <para>The files are copied next to the binary by the csproj (they are <c>Content</c> items
    /// under <c>Assets\</c>, generated by unigram-linux/tools/gen-linux-csproj.py), which is why
    /// <see cref="AppContext.BaseDirectory"/> and not the working directory is the anchor: it is
    /// the directory of Unigram.dll no matter how the process was started.</para>
    /// </summary>
    internal static class NativeAssets
    {
        /// <summary>
        /// The language identification model: a flatbuffer, not a JPEG. The extension is upstream's
        /// trick to stop the Windows packager from compressing it, and it is kept so the file is
        /// the same one on both platforms.
        /// </summary>
        public const string LanguageModel = "langid_model.smfb.jpg";

        /// <summary>
        /// libprisma's compiled grammars (~600 KB). Lives in Libraries/libprisma/libprisma in the
        /// repo; the Windows packaging copies it to Assets\, and so does ours.
        /// </summary>
        public const string Grammars = "grammars.dat";

        /// <summary>
        /// Directory override for the whole set, for running out of a build tree or a spike.
        /// </summary>
        private const string DirectoryVariable = "UNIGRAM_ASSETS_PATH";

        /// <summary>
        /// Absolute path of <paramref name="fileName"/>, or null when it is nowhere to be found --
        /// which every caller has to tolerate, because a missing model only costs the feature that
        /// needs it, never the app.
        /// </summary>
        /// <param name="fileName">Bare file name, e.g. <see cref="Grammars"/>.</param>
        /// <param name="variable">
        /// Name of an environment variable holding the full path of this one file, checked first.
        /// Development override; unset in a real install.
        /// </param>
        public static string Resolve(string fileName, string variable)
        {
            try
            {
                if (!string.IsNullOrEmpty(variable))
                {
                    var overridden = Environment.GetEnvironmentVariable(variable);
                    if (!string.IsNullOrEmpty(overridden) && File.Exists(overridden))
                    {
                        return Path.GetFullPath(overridden);
                    }
                }

                var directory = Environment.GetEnvironmentVariable(DirectoryVariable);
                if (!string.IsNullOrEmpty(directory))
                {
                    var candidate = Path.Combine(directory, fileName);
                    if (File.Exists(candidate))
                    {
                        return Path.GetFullPath(candidate);
                    }
                }

                var baseDirectory = AppContext.BaseDirectory;

                // Where the csproj puts them, and where a packaged build will have them.
                var asset = Path.Combine(baseDirectory, "Assets", fileName);
                if (File.Exists(asset))
                {
                    return asset;
                }

                // Flat next to the binary: how the spikes and a single-file publish end up.
                var flat = Path.Combine(baseDirectory, fileName);
                if (File.Exists(flat))
                {
                    return flat;
                }
            }
            catch (Exception ex) when (ex is ArgumentException or IOException or UnauthorizedAccessException)
            {
                // A malformed override path is not worth taking the feature down for.
                UnigramNative.Report(Logger.LogLevel.Warning, $"assets: cannot resolve {fileName}: {ex.Message}");
            }

            return null;
        }
    }
}
