//
// Copyright (c) Fela Ameghino 2015-2026
//
// Distributed under the GNU General Public License v3.0. (See accompanying
// file LICENSE or copy at https://www.gnu.org/licenses/gpl-3.0.txt)
//

// Telegram.Assets.Icons is generated by LottieGen on Windows (Win2D based). The icons that
// the Phase 1 XAML instantiates are declared here as inert animated visual sources, so the
// AnimatedIcon falls back to nothing and the glyph of the hosting button is what gets drawn.

using System.Collections.Generic;
using Microsoft.UI.Composition;
using Microsoft.UI.Xaml.Controls;
using Windows.Foundation;
using Windows.UI;

namespace Telegram.Assets.Icons
{
    // Uno's IAnimatedVisualSource adds a player-driven lifecycle (Load/Play/Measure/...)
    // on top of the WinUI one; every member is a no-op here.
    public abstract partial class InertAnimatedVisualSource : IAnimatedVisualSource2
    {
        public IReadOnlyDictionary<string, double> Markers { get; } = new Dictionary<string, double>();

        public void SetColorProperty(string propertyName, Color value)
        {
        }

        public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            return null;
        }

        public void Update(AnimatedVisualPlayer player)
        {
        }

        public void Load()
        {
        }

        public void Unload()
        {
        }

        public void Play(double fromProgress, double toProgress, bool looped)
        {
        }

        public void Stop()
        {
        }

        public void Pause()
        {
        }

        public void Resume()
        {
        }

        public void SetProgress(double progress)
        {
        }

        public Size Measure(Size availableSize)
        {
            return new Size(0, 0);
        }
    }

    public sealed partial class MuteUnmute : InertAnimatedVisualSource
    {
    }

    public sealed partial class VoiceVideo2 : InertAnimatedVisualSource
    {
    }

    // The "transcribe" toggle of a voice note (VoiceNoteContent.xaml). Its template has no
    // FallbackIconSource either, so with an inert source the 28 px button draws its background and
    // nothing else - the same cosmetic loss as the settings rows above.
    public sealed partial class VoiceRecognition : InertAnimatedVisualSource
    {
    }

    // The three dots of a transcription still in progress. Unlike the others this one is built
    // from code (VoiceNoteContent.LoadPending), with a colour bound to the text, so it keeps a
    // Foreground the caller can set; TryCreateAnimatedVisual still answers null, and the call site
    // has an #if LINUX that stops there instead of dereferencing it.
    public sealed partial class Dots : InertAnimatedVisualSource
    {
        public Color Foreground { get; set; }
    }

    // The rows of the settings root (Views/SettingsPage.xaml). IconBadgeButtonStyle draws them
    // through muxc:AnimatedIcon and that template has no FallbackIconSource, so with an inert
    // source the 48 px icon column is simply empty - the row's text, badge and chevron are
    // unaffected. Cosmetic, and the only way back is a LottieGen replacement (phase 3).
    public sealed partial class Profile : InertAnimatedVisualSource
    {
    }

    public sealed partial class Appearance : InertAnimatedVisualSource
    {
    }

    public sealed partial class Privacy : InertAnimatedVisualSource
    {
    }

    public sealed partial class Notifications : InertAnimatedVisualSource
    {
    }

    public sealed partial class Data : InertAnimatedVisualSource
    {
    }

    public sealed partial class PowerSaving : InertAnimatedVisualSource
    {
    }

    public sealed partial class Folders : InertAnimatedVisualSource
    {
    }

    public sealed partial class Devices : InertAnimatedVisualSource
    {
    }

    public sealed partial class Language : InertAnimatedVisualSource
    {
    }

    public sealed partial class Advanced : InertAnimatedVisualSource
    {
    }

    public sealed partial class AskQ : InertAnimatedVisualSource
    {
    }

    public sealed partial class FAQ : InertAnimatedVisualSource
    {
    }

    public sealed partial class Tips : InertAnimatedVisualSource
    {
    }

    public sealed partial class PrivacyPolicy : InertAnimatedVisualSource
    {
    }
    // u-003: the six morph animations the sticker button plays between its Emoji / Stickers / GIF
    // states (Assets/Icons/{EmojiToSticker,EmojiToGif,StickerToEmoji,StickerToGif,GifToEmoji,
    // GifToSticker}.cs). Same treatment as the other eighteen: LottieGen output is Win2D, so the
    // source is inert and the button falls back to its glyph, which ChatStickerButton sets from
    // Icons.Emoji24 / Sticker24 / Gif24 -- font glyphs, so the button still shows the right icon
    // for the current tab. What is lost is only the morph between them.
    public sealed partial class EmojiToSticker : InertAnimatedVisualSource
    {
    }

    public sealed partial class EmojiToGif : InertAnimatedVisualSource
    {
    }

    public sealed partial class StickerToEmoji : InertAnimatedVisualSource
    {
    }

    public sealed partial class StickerToGif : InertAnimatedVisualSource
    {
    }

    public sealed partial class GifToEmoji : InertAnimatedVisualSource
    {
    }

    public sealed partial class GifToSticker : InertAnimatedVisualSource
    {
    }

}
