// <autogenerated /> por unigram-linux/tools/gen-linux-csproj.py: no editar a mano.
// Diccionarios fusionados por el XAML del subconjunto que no forman parte de la fase 1 (7).
// Uno lanza "Cannot locate resource" al materializar un diccionario cuyo Source no está registrado;
// un diccionario vacío mantiene vivo el resto (los StaticResource que dependan de ellos fallan solo
// cuando se aplica esa plantilla concreta).
using System;
using Microsoft.UI.Xaml;

namespace Telegram
{
    public static class MissingDictionaries
    {
        public static void Register()
        {
            Register("ms-appx:///Controls/Messages/Content/DiceContent.xaml");
            Register("ms-appx:///Controls/Messages/Content/InstantContent.xaml");
            Register("ms-appx:///Controls/Messages/Content/PaidMediaContent.xaml");
            Register("ms-appx:///Controls/Messages/Content/PreviewContent.xaml");
            Register("ms-appx:///Controls/Messages/Content/StakeDiceContent.xaml");
            Register("ms-appx:///Controls/Messages/MessageFactCheck.xaml");
            Register("ms-appx:///Controls/Messages/MessageSummary.xaml");
        }

        private static void Register(string uri)
        {
            global::Uno.UI.ResourceResolver.RegisterResourceDictionaryBySource(uri, context: null, dictionary: () => new ResourceDictionary());
        }
    }
}
